




/*
     FILE ARCHIVED ON 10:42:44 мар 26, 2016 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 3:30:03 ноя 27, 2016.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
*/
THREE.OBJLoader=function(e){this.manager=void 0!==e?e:THREE.DefaultLoadingManager},THREE.OBJLoader.prototype={constructor:THREE.OBJLoader,load:function(e,t){var n=this,r=new THREE.XHRLoader(n.manager);r.setCrossOrigin(this.crossOrigin),r.load(e,function(e){t(n.parse(e))})},parse:function(e){function t(e,t,n){return new THREE.Vector3(e,t,n)}function n(e,t){return new THREE.Vector2(e,t)}function r(e,t,n,r){return new THREE.Face3(e,t,n,r)}function a(e,t,n,a){void 0===a?o.faces.push(r(parseInt(e)-(u+1),parseInt(t)-(u+1),parseInt(n)-(u+1))):o.faces.push(r(parseInt(e)-(u+1),parseInt(t)-(u+1),parseInt(n)-(u+1),[E[parseInt(a[0])-1].clone(),E[parseInt(a[1])-1].clone(),E[parseInt(a[2])-1].clone()]))}function d(e,t,n){o.faceVertexUvs[0].push([h[parseInt(e)-1].clone(),h[parseInt(t)-1].clone(),h[parseInt(n)-1].clone()])}function s(e,t,n){void 0===e[3]?(a(e[0],e[1],e[2],n),void 0!==t&&t.length>0&&d(t[0],t[1],t[2])):(void 0!==n&&n.length>0?(a(e[0],e[1],e[3],[n[0],n[1],n[3]]),a(e[1],e[2],e[3],[n[1],n[2],n[3]])):(a(e[0],e[1],e[3]),a(e[1],e[2],e[3])),void 0!==t&&t.length>0&&(d(t[0],t[1],t[3]),d(t[1],t[2],t[3])))}var o,l,c,i=new THREE.Object3D,u=0;/^o /gm.test(e)===!1&&(o=new THREE.Geometry,l=new THREE.MeshLambertMaterial,c=new THREE.Mesh(o,l),i.add(c));for(var p=0,E=[],h=[],f=/v( +[\d|\.|\+|\-|e]+)( +[\d|\.|\+|\-|e]+)( +[\d|\.|\+|\-|e]+)/,v=/vn( +[\d|\.|\+|\-|e]+)( +[\d|\.|\+|\-|e]+)( +[\d|\.|\+|\-|e]+)/,g=/vt( +[\d|\.|\+|\-|e]+)( +[\d|\.|\+|\-|e]+)/,m=/f( +\d+)( +\d+)( +\d+)( +\d+)?/,H=/f( +(\d+)\/(\d+))( +(\d+)\/(\d+))( +(\d+)\/(\d+))( +(\d+)\/(\d+))?/,R=/f( +(\d+)\/(\d+)\/(\d+))( +(\d+)\/(\d+)\/(\d+))( +(\d+)\/(\d+)\/(\d+))( +(\d+)\/(\d+)\/(\d+))?/,T=/f( +(\d+)\/\/(\d+))( +(\d+)\/\/(\d+))( +(\d+)\/\/(\d+))( +(\d+)\/\/(\d+))?/,I=e.split("\n"),w=0;w<I.length;w++){var F=I[w];F=F.trim();var x;0!==F.length&&"#"!==F.charAt(0)&&(null!==(x=f.exec(F))?o.vertices.push(t(parseFloat(x[1]),parseFloat(x[2]),parseFloat(x[3]))):null!==(x=v.exec(F))?E.push(t(parseFloat(x[1]),parseFloat(x[2]),parseFloat(x[3]))):null!==(x=g.exec(F))?h.push(n(parseFloat(x[1]),parseFloat(x[2]))):null!==(x=m.exec(F))?s([x[1],x[2],x[3],x[4]]):null!==(x=H.exec(F))?s([x[2],x[5],x[8],x[11]],[x[3],x[6],x[9],x[12]]):null!==(x=R.exec(F))?s([x[2],x[6],x[10],x[14]],[x[3],x[7],x[11],x[15]],[x[4],x[8],x[12],x[16]]):null!==(x=T.exec(F))?s([x[2],x[5],x[8],x[11]],[],[x[3],x[6],x[9],x[12]]):/^o /.test(F)?(void 0!==o&&(u+=o.vertices.length),o=new THREE.Geometry,l=new THREE.MeshLambertMaterial,c=new THREE.Mesh(o,l),c.name=F.substring(2).trim(),i.add(c),p=0):/^g /.test(F)||(/^usemtl /.test(F)?l.name=F.substring(7).trim():/^mtllib /.test(F)||/^s /.test(F)))}for(var w=0,L=i.children.length;L>w;w++){var o=i.children[w].geometry;o.computeCentroids(),o.computeFaceNormals(),o.computeBoundingSphere()}return i}};